### ISSUE TITLE
Faça as tabelas me envie por email.

### ISSUE THREAD

**Issue by ghost** [virginiadev9/materiaisreciclaveis#2]
Faça um rascunho das tabelas ja padronizadas e envie no email: clodoaldo.neto.116@ufrn.edu.br , se tiver duvida conversamos por lá também pq adianta muito ja ter as tabelas do bd corretas e organizadas de acordo com seu problem... @virginiadev9

**Comment by virginiadev9** [comment]
ok, vou enviar lá, hoje la pelas 21h te envio.
